Require 'jruby' in bson_java.rb
This prevents bson from failing with the following error on JRuby 1.7.0:

    NoMethodError: undefined method `runtime' for JRuby:Module
                    serialize at .../gems/bson-1.7.0-java/lib/bson/bson_java.rb:9