Revert "Solves: "gems/mongo-1.6.0/lib/mongo/util/logging.rb:34:in `instrument': undefined method `level' for #<Mongoid::Logger:0x00000103ca7570> (NoMethodError)""
This reverts commit 775ed49e6cbd3554a130b5122d0d4ac4e3e5e862.

a logger should quack like a logger